### ISSUE TITLE
Sometimes generating a name adds "-" characters

### ISSUE THREAD

**Issue by drewry** [opendnd/nomina#2]
When generating a name it sometimes comes out like: `Yui--` need to find a way to fix the root problem or add something like `name.replace(/\-/g, '')`

**Comment by drewry** [comment]
I think this is fixed in c5f7f70d9ab6c869c3aab75a79a8f0a0e942d352

**Comment by naltun** [comment]
Which file was causing the issue, and which lines?

**Comment by drewry** [comment]
Looks like the offending line is here https://github.com/opendnd/nomina/blob/907f22d3b39145f39b97f484f1ae0fa645c1dc04/lib/generator.js#L156

However we don’t want to get rid of that as it’s a feature of the Markov chain. Looks like replace after generating is the best option for now.
